#pragma once
// Copy to include/local_config.h. This file is ignored by Git.
#define WIFI_SSID_VALUE "YOUR_WIFI_2_4_GHZ"
#define WIFI_PASSWORD_VALUE "YOUR_WIFI_PASSWORD"
#define ASSISTANT_BASE_URL_VALUE "https://asistente-cloud-erp-7474651957738908.aws.databricksapps.com"
#define DATABRICKS_WORKSPACE_URL_VALUE "https://dbc-a1aca8aa-28bd.cloud.databricks.com"
#define DATABRICKS_CLIENT_ID_VALUE "YOUR_DATABRICKS_SERVICE_PRINCIPAL_CLIENT_ID"
#define DATABRICKS_CLIENT_SECRET_VALUE "YOUR_DATABRICKS_SERVICE_PRINCIPAL_OAUTH_SECRET"
#define ESP32_API_TOKEN_VALUE "YOUR_ESP32_DEVICE_TOKEN"
// #define DEVICE_ID_VALUE "panel-4848s040-3c-01"
#define DEFAULT_3C_COMMAND_VALUE "Cambia la tarea J10 a mensual"
#define PANEL_AUDIO_ENABLED_VALUE 1
#define PANEL_BRIGHTNESS_VALUE 180
